name: Benchmarks for Yamson

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout yamson code
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run benchmarks
        run: cargo bench --workspace --all-targets --verbose

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion
